/* Copyright (C) 2018 Arribada
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#include "bsp.h"

///////////////////////////////// GPIO definitions ////////////////////////////////
GPIO_InitTypeDefAndPort_t GPIO_Inits[GPIO_TOTAL_NUMBER] =
{
    // Port, Pin, Mode, Pull, Speed, Alternate
    {GPIOE, {GPIO_PIN_3,  GPIO_MODE_OUTPUT_PP,         GPIO_NOPULL,   GPIO_SPEED_FREQ_LOW, 0}}, // GPIO_SPARE_GPIO
    {GPIOD, {GPIO_PIN_7,  GPIO_MODE_INPUT,             GPIO_NOPULL,   GPIO_SPEED_FREQ_LOW, 0}}, // GPIO_1PPS
    {GPIOD, {GPIO_PIN_5,  GPIO_MODE_OUTPUT_PP,         GPIO_NOPULL,   GPIO_SPEED_FREQ_LOW, 0}}, // GPIO_1
    {GPIOC, {GPIO_PIN_11, GPIO_MODE_OUTPUT_PP,         GPIO_NOPULL,   GPIO_SPEED_FREQ_LOW, 0}}, // GPIO_2
    {GPIOF, {GPIO_PIN_6,  GPIO_MODE_OUTPUT_PP,         GPIO_NOPULL,   GPIO_SPEED_FREQ_LOW, 0}}, // GPIO_3
    {GPIOA, {GPIO_PIN_9,  GPIO_MODE_IT_RISING_FALLING, GPIO_PULLDOWN, GPIO_SPEED_FREQ_LOW, 0}}, // GPIO_VUSB
    {GPIOE, {GPIO_PIN_14, GPIO_MODE_IT_RISING_FALLING, GPIO_NOPULL,   GPIO_SPEED_FREQ_LOW, 0}}, // GPIO_SWS
    {GPIOB, {GPIO_PIN_2,  GPIO_MODE_IT_RISING_FALLING, GPIO_NOPULL,   GPIO_SPEED_FREQ_LOW, 0}}, // GPIO_REED_SW
    {GPIOA, {GPIO_PIN_4,  GPIO_MODE_OUTPUT_PP,         GPIO_NOPULL,   GPIO_SPEED_FREQ_LOW, 0}}, // GPIO_SPI1_CS_BT
    {GPIOC, {GPIO_PIN_6,  GPIO_MODE_OUTPUT_PP,         GPIO_NOPULL,   GPIO_SPEED_FREQ_LOW, 0}}, // GPIO_SPI2_CS_ARG
    {GPIOD, {GPIO_PIN_0,  GPIO_MODE_OUTPUT_PP,         GPIO_NOPULL,   GPIO_SPEED_FREQ_LOW, 0}}, // GPIO_SPI2_CS_FLASH
    {GPIOE, {GPIO_PIN_8,  GPIO_MODE_OUTPUT_OD,         GPIO_NOPULL,   GPIO_SPEED_FREQ_LOW, 0}}, // GPIO_GPOUT
    {GPIOA, {GPIO_PIN_1,  GPIO_MODE_OUTPUT_PP,         GPIO_NOPULL,   GPIO_SPEED_FREQ_LOW, 0}}, // GPIO_BT_GPIO
    {GPIOB, {GPIO_PIN_1,  GPIO_MODE_INPUT,             GPIO_NOPULL,   GPIO_SPEED_FREQ_LOW, 0}}, // GPIO_USB_ID
    {GPIOE, {GPIO_PIN_9,  GPIO_MODE_OUTPUT_PP,         GPIO_NOPULL,   GPIO_SPEED_FREQ_LOW, 0}}, // GPIO_AUX_EN
    {GPIOE, {GPIO_PIN_11, GPIO_MODE_OUTPUT_PP,         GPIO_NOPULL,   GPIO_SPEED_FREQ_LOW, 0}}, // GPIO_LED1_GREEN
    {GPIOE, {GPIO_PIN_13, GPIO_MODE_OUTPUT_PP,         GPIO_NOPULL,   GPIO_SPEED_FREQ_LOW, 0}}, // GPIO_LED2_RED
    {GPIOD, {GPIO_PIN_13, GPIO_MODE_INPUT,             GPIO_NOPULL,   GPIO_SPEED_FREQ_LOW, 0}}, // GPIO_DRDY_M
    {GPIOD, {GPIO_PIN_10, GPIO_MODE_INPUT,             GPIO_NOPULL,   GPIO_SPEED_FREQ_LOW, 0}}, // GPIO_INT_M
    {GPIOB, {GPIO_PIN_13, GPIO_MODE_INPUT,             GPIO_NOPULL,   GPIO_SPEED_FREQ_LOW, 0}}, // GPIO_DEN_AG
    {GPIOE, {GPIO_PIN_15, GPIO_MODE_IT_RISING,         GPIO_NOPULL,   GPIO_SPEED_FREQ_LOW, 0}}, // GPIO_INT1_AG
    {GPIOB, {GPIO_PIN_12, GPIO_MODE_INPUT,             GPIO_NOPULL,   GPIO_SPEED_FREQ_LOW, 0}}, // GPIO_INT2_AG

    {GPIOB, {GPIO_PIN_6,  GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF0_USART1}}, // GPIO_UART1_TX
    {GPIOB, {GPIO_PIN_7,  GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF0_USART1}}, // GPIO_UART1_RX

    {GPIOA, {GPIO_PIN_2,  GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF1_USART2}}, // GPIO_UART2_TX

    {GPIOD, {GPIO_PIN_8,  GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF0_USART3}}, // GPIO_UART3_TX
    {GPIOD, {GPIO_PIN_9,  GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF0_USART3}}, // GPIO_UART3_RX
    {GPIOD, {GPIO_PIN_12, GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF0_USART3}}, // GPIO_UART3_RTS
    {GPIOD, {GPIO_PIN_11, GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF0_USART3}}, // GPIO_UART3_CTS

    {GPIOB, {GPIO_PIN_8,  GPIO_MODE_AF_OD, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF1_I2C1}}, // GPIO_I2C1_SCL
    {GPIOB, {GPIO_PIN_9,  GPIO_MODE_AF_OD, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF1_I2C1}}, // GPIO_I2C1_SDA

    {GPIOB, {GPIO_PIN_10, GPIO_MODE_AF_OD, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF1_I2C2}}, // GPIO_I2C2_SCL
    {GPIOB, {GPIO_PIN_11, GPIO_MODE_AF_OD, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF1_I2C2}}, // GPIO_I2C2_SDA

    {GPIOA, {GPIO_PIN_5,  GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF0_SPI1}}, // GPIO_SPI1_SCK
    {GPIOA, {GPIO_PIN_6,  GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF0_SPI1}}, // GPIO_SPI1_MISO
    {GPIOA, {GPIO_PIN_7,  GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF0_SPI1}}, // GPIO_SPI1_MOSI

    {GPIOD, {GPIO_PIN_1,  GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF1_SPI2}}, // GPIO_SPI2_SCK
    {GPIOD, {GPIO_PIN_3,  GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF1_SPI2}}, // GPIO_SPI2_MISO
    {GPIOD, {GPIO_PIN_4,  GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH, GPIO_AF1_SPI2}}, // GPIO_SPI2_MOSI
};

///////////////////////////////// SPI definitions /////////////////////////////////
const SPI_InitTypeDefAndInst_t SPI_Inits[SPI_TOTAL_NUMBER] =
{
    // Instance, Mode, Direction, DataSize, CLKPolarity, CLKPhase, NSS, BaudRatePrescaler, FirstBit, TIMode, CRCCalculation, CRCPolynomial, CRCLength, NSSPMode
    {SPI1, {SPI_MODE_MASTER, SPI_DIRECTION_2LINES, SPI_DATASIZE_8BIT, SPI_POLARITY_LOW, SPI_PHASE_1EDGE, SPI_NSS_SOFT, SPI_BAUDRATEPRESCALER_8, SPI_FIRSTBIT_MSB, SPI_TIMODE_DISABLE, SPI_CRCCALCULATION_DISABLE, 7, SPI_CRC_LENGTH_DATASIZE, SPI_NSS_PULSE_ENABLE}},
    {SPI2, {SPI_MODE_MASTER, SPI_DIRECTION_2LINES, SPI_DATASIZE_8BIT, SPI_POLARITY_LOW, SPI_PHASE_1EDGE, SPI_NSS_SOFT, SPI_BAUDRATEPRESCALER_4, SPI_FIRSTBIT_MSB, SPI_TIMODE_DISABLE, SPI_CRCCALCULATION_DISABLE, 7, SPI_CRC_LENGTH_DATASIZE, SPI_NSS_PULSE_ENABLE}},
};

///////////////////////////////// I2C definitions /////////////////////////////////
const I2C_InitTypeDefAndInst_t I2C_Inits[I2C_TOTAL_NUMBER] =
{
    // Instance, Timing, OwnAddress1, AddressingMode, DualAddressMode, OwnAddress2, OwnAddress2Masks, GeneralCallMode, NoStretchMode
    {I2C1, {0x2010091A, 0, I2C_ADDRESSINGMODE_7BIT, I2C_DUALADDRESS_DISABLE, 0, I2C_OA2_NOMASK, I2C_GENERALCALL_DISABLE, I2C_NOSTRETCH_DISABLE}},
    {I2C2, {0x2010091A, 0, I2C_ADDRESSINGMODE_7BIT, I2C_DUALADDRESS_DISABLE, 0, I2C_OA2_NOMASK, I2C_GENERALCALL_DISABLE, I2C_NOSTRETCH_DISABLE}},
};

///////////////////////////////// UART definitions ////////////////////////////////
const UART_InitTypeDefAndInst_t UART_Inits[UART_TOTAL_NUMBER] =
{
    // Instance,BaudRate,WordLength,StopBits,Parity,Mode,HwFlowCtl,OverSampling,OneBitSampling
    {USART1, {9600,    UART_WORDLENGTH_8B, UART_STOPBITS_1, UART_PARITY_NONE, UART_MODE_TX_RX, UART_HWCONTROL_NONE,    UART_OVERSAMPLING_16, UART_ADVFEATURE_NO_INIT}},
    {USART2, {3000000, UART_WORDLENGTH_8B, UART_STOPBITS_1, UART_PARITY_NONE, UART_MODE_TX,    UART_HWCONTROL_NONE,    UART_OVERSAMPLING_16, UART_ADVFEATURE_NO_INIT}},
    {USART3, {9600,    UART_WORDLENGTH_8B, UART_STOPBITS_1, UART_PARITY_NONE, UART_MODE_TX_RX, UART_HWCONTROL_RTS_CTS, UART_OVERSAMPLING_16, UART_ADVFEATURE_NO_INIT}},
};

///////////////////////////////// IWDG definitions ////////////////////////////////

// NOTE: This can't be const since it must be accessed from RAM during FW update procedure
IWDG_HandleTypeDef IWDG_Init =
{
    IWDG,
    {
        .Prescaler = IWDG_PRESCALER_256,  /* 6 => 40 KHz / 256 pre-scaler = 156.25 Hz tick period */
        .Reload = 3125,  /* Equates to 20 seconds */
        .Window = 0x00000FFF
    }
};
