AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  ArribadaPushShadowDynamoDBFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Timeout: 10
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: "*"
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: "*"

      Handler: app.lambda_handler
      Runtime: python3.7
      CodeUri: push_shadow_dynamodb/
    Events:
      IoTLoggingMessage:
        Type: IOTRule
        Properties:
          Sql: "SELECT * AS update, topic(3) as thing_name FROM '$aws/things/+/shadow/update/documents'"
