pipeline {
    agent {
        dockerfile {
            args '-v ${PWD}:/usr/src/app -w /usr/src/app'
            reuseNode true
        }
    }

    stages {
        stage ('Compile Bootloader') {
            steps {
                sh 'git clean -fdx'
                sh 'mkdir -p ports/nrf52840/bootloader/build'
                dir('ports/nrf52840/bootloader/build') {
                    sh 'cmake --no-cache -DCMAKE_TOOLCHAIN_FILE=../../toolchain_arm_gcc_nrf52.cmake ..'
                    sh 'make -j$(nproc)'
                }
                // Append the git commit details to the filename names
                sh '''
                    folder=ports/nrf52840/bootloader/build/
                    for file in $folder*.hex $folder*.bin $folder*.map ; do
                        basename=${file%.*}
                        extension=${file##*.}
                        mv "$file" "$basename"_"$(git describe --always --tags).$extension" || true
                    done
                '''
            }
            post { 
                success { 
                archiveArtifacts 'ports/nrf52840/bootloader/build/*.hex,ports/nrf52840/bootloader/build/*.map'
                }
            }
        }

        stage ('Compile Firmware') {
            steps {
                sh 'mkdir -p ports/nrf52840/build'
                dir('ports/nrf52840/build') {
                    // Debug build
                    sh 'cmake --no-cache -DCMAKE_TOOLCHAIN_FILE=../toolchain_arm_gcc_nrf52.cmake -DCMAKE_BUILD_TYPE=Debug ..'
                    sh 'make -j$(nproc)'
                    // Release build
                    sh 'cmake --no-cache -DCMAKE_TOOLCHAIN_FILE=../toolchain_arm_gcc_nrf52.cmake -DCMAKE_BUILD_TYPE=Release ..'
                    sh 'make -j$(nproc)'
                }
                // Append the git commit details to the filename names
                sh '''
                    folder=ports/nrf52840/build/
                    for file in $folder*.hex $folder*.bin $folder*.map $folder*.out $folder*.zip ; do
                        basename=${file%.*}
                        extension=${file##*.}
                        mv "$file" "$basename"_"$(git describe --always --tags).$extension" || true
                    done
                '''
            }
            post { 
                success { 
                archiveArtifacts 'ports/nrf52840/build/*.hex,ports/nrf52840/build/*.bin,ports/nrf52840/build/*.map,ports/nrf52840/build/*.out,ports/nrf52840/build/*.zip'
                }
            }
        }

        stage ('Compile Unit Tests') {
            steps {
                sh '''
                cd tests
                bash ./build_tests.sh
                '''
            }
        }

        stage ('Run Unit Tests') {
            steps {
                sh '''
                cd tests
                bash ./run_tests.sh --intensive
                '''
            }
        }

        stage ('Run CPD Code Duplication Analysis') {
            steps {
                dir('ports/nrf52840/build') {
                    sh '''
                    make cpd
                    '''
                }
            }
        }

        stage ('Run Clang Static Analysis') {
            steps {
                sh 'mkdir -p ports/nrf52840/clang_build'
                dir('ports/nrf52840/clang_build') {
                    sh '''
                    cmake --no-cache -DCMAKE_C_COMPILER=ccc-analyzer -DCMAKE_BUILD_TYPE=Debug ..
                    scan-build --use-cc=`which arm-none-eabi-gcc` --analyzer-target=arm-none-eabi-gcc --use-analyzer=`which clang` -plist-html -maxloop 1000 -o ./report make -j$(nproc)
                    '''
                }
            }
        }

        stage ('Run CppCheck') {
            steps {
                dir('ports/nrf52840/build') {
                    sh 'make cppcheck'
                }
            }
        }

        stage ('Generate Reports') {
            steps {
                // Generate the test coverage file for the Cobertura report
                sh 'gcovr -r $WORKSPACE -e \'tests/\' --xml > coverage.xml'

                // Publish reports from static analysis tools
                recordIssues(tools: [cppCheck(pattern: 'ports/nrf52840/build/cppcheck.xml'), cpd(pattern: '**/cpd.xml'), taskScanner(includePattern: '**/*.c,**/*.cpp,**/*.h', excludePattern: '**/ports/nrf52840/drivers/nRF5_SDK_15.2.0/**,**/ports/nrf52840/drivers/nRF5_SDK_15.3.0/**,**/tests/src/cmock/**,**/tests/src/googletest-release-1.8.1/**', lowTags: 'WARN', normalTags: 'TODO', highTags: 'FIXME')])
                xunit thresholds: [failed(unstableNewThreshold: '0', unstableThreshold: '0')], tools: [CTest(deleteOutputFiles: true, failIfNotNew: true, pattern: 'tests/src/build/Testing/**/Test.xml', skipNoTestFiles: false, stopProcessingIfError: true)]
                cobertura autoUpdateHealth: false, autoUpdateStability: false, coberturaReportFile: '**coverage.xml', conditionalCoverageTargets: '70, 0, 0', failUnhealthy: false, failUnstable: false, lineCoverageTargets: '80, 0, 0', maxNumberOfBuilds: 0, methodCoverageTargets: '80, 0, 0', onlyStable: false, sourceEncoding: 'ASCII', zoomCoverageChart: false
            }
        }
    }
}