/* Copyright (C) 2019 Arribada
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef _VERSION_H_
#define _VERSION_H_

#ifndef GIT_VERSION // This is generated by the makefile
#define GIT_VERSION "GIT_VERSION undefined"
#endif

#define COMPILE_DATE __DATE__
#define COMPILE_TIME __TIME__

#if defined(__GNUC__)
#define COMPILER_NAME "GCC V"__VERSION__
#define COMPILER_VERSION (__GNUC__ * 10000 \
                     + __GNUC_MINOR__ * 100 \
                     + __GNUC_PATCHLEVEL__)
#ifndef GTEST
#if COMPILER_VERSION != 70301UL
#warning "This GCC version is untested. Please use gcc-arm-none-eabi-7-2018-q2-update"
#endif
#endif
#else
#warning "Only GCC has been tested"
#define COMPILER_NAME "Unknown"
#define COMPILER_VERSION 0U
#endif

#endif /* _VERSION_H_ */
